general_cfg:
  joyrl_version: 0.6.5
  algo_name: DoubleDQN
  env_name: gym
  interactor_device: cpu
  learner_device: cpu 
  seed: 1
  mode: train
  max_episode: -1 
  max_step: 200
  load_checkpoint: false
  load_path: Train_CartPole-v1_DQN_20221026-054757
  load_model_step: best
  online_eval: true 
  online_eval_episode: 10
  model_save_fre: 500
  policy_summary_fre: 100

algo_cfg:
  learn_frequency: 1
  # branch_layers:
  #   - name: feature_1
  #     layers: 
  #       - layer_type: linear
  #         layer_size: [256]
  #         activation: relu
  #       - layer_type: linear
  #         layer_size: [256]
  #         activation: relu
  #   - name: feature_2
  #     layers: 
  #       - layer_type: linear
  #         layer_size: [256]
  #         activation: relu
  #       - layer_type: linear
  #         layer_size: [256]
  #         activation: relu
  merge_layers:
    - layer_type: linear
      layer_size: [256]
      activation: relu
    - layer_type: linear
      layer_size: [256]
      activation: relu
  batch_size: 128
  buffer_type: REPLAY_QUE
  max_buffer_size: 100000
  epsilon_decay: 500
  epsilon_end: 0.01
  epsilon_start: 0.95
  gamma: 0.99
  lr: 0.0001
  target_update: 4
env_cfg:
  id: CartPole-v1
  render_mode: null
  wrappers:
    - wrapper_name: MultiHeadObsWrapper
    - wrapper_name: MultiHeadActionWrapper