general_cfg:
  joyrl_version: 0.6.7.2
  algo_name: DDPG
  env_name: gym 
  device: cpu 
  mode: train 
  load_checkpoint: false
  load_path: Train_ray_Pendulum-v1_DDPG_20230527-001715 
  load_model_step: best 
  max_episode: -1 
  max_step: 200 
  seed: 1
  online_eval: true 
  online_eval_episode: 20 
  model_save_fre: 500 
algo_cfg:
  action_space:
    type: [dpg]
  actor_branch_layers:
    - name: state
      layers:
      - layer_type: linear
        layer_size: [256]
        activation: relu
      - layer_type: linear
        layer_size: [256]
        activation: relu
  critic_branch_layers:
    - name: state
      layers:
      - layer_type: none
    - name: action
      layers:
      - layer_type: none
  critic_merge_layers:
    - layer_type: linear
      layer_size: [256]
      activation: relu
    - layer_type: linear
      layer_size: [256]
      activation: relu
  batch_size: 256
  buffer_type: REPLAY_QUE
  max_buffer_size: 8000
  actor_lr: 0.0001
  critic_lr: 0.001
  policy_loss_weight: 0.002
  gamma: 0.99
  tau: 0.01
env_cfg:
  id: Pendulum-v1
  render_mode: null # null, rgb_array, human
  wrappers:
    - wrapper_name: MultiHeadObsWrapper