general_cfg:
  joyrl_version: 0.5.2
  algo_name: TD3
  env_name: gym 
  device: cpu 
  mode: train 
  load_checkpoint: false
  load_path: Train_ray_Pendulum-v1_DDPG_20230527-001715 
  load_model_step: best 
  max_episode: 400 
  max_step: 200 
  seed: 1
  online_eval: true 
  online_eval_episode: 20 
  model_save_fre: 2000 
algo_cfg:
  learn_frequency: 1
  actor_branch_layers:
    - name: state
      layers:
      - layer_type: linear
        layer_size: [256]
        activation: tanh
      - layer_type: linear
        layer_size: [256]
        activation: tanh
  critic_branch_layers:
    - name: state
      layers:
      - layer_type: none
    - name: action
      layers:
      - layer_type: none
  critic_merge_layers:
    - layer_type: linear
      layer_size: [256]
      activation: tanh
    - layer_type: linear
      layer_size: [256]
      activation: tanh
  batch_size: 128
  buffer_type: REPLAY_QUE
  max_buffer_size: 8000
  actor_lr: 0.001
  critic_lr: 0.001
  policy_loss_weight: 0.002
  gamma: 0.99
  tau: 0.005
env_cfg:
  id: Pendulum-v1
  render_mode: null 